/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.recipedsl.ui.internal.RecipedslActivator;

public class RecipeDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RecipedslActivator.getInstance().getInjector("org.xtext.example.mydsl.RecipeDSL");
	}

}
