/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.RecipeDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RecipeDSLStandaloneSetup extends RecipeDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new RecipeDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
