/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalRecipeDSLParser;
import org.xtext.example.mydsl.services.RecipeDSLGrammarAccess;

public class RecipeDSLParser extends AbstractContentAssistParser {

	@Inject
	private RecipeDSLGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalRecipeDSLParser createParser() {
		InternalRecipeDSLParser result = new InternalRecipeDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getLevelAccess().getNameAlternatives_1_0(), "rule__Level__NameAlternatives_1_0");
					put(grammarAccess.getIngredientAccess().getAlternatives(), "rule__Ingredient__Alternatives");
					put(grammarAccess.getWeightAccess().getAlternatives_1(), "rule__Weight__Alternatives_1");
					put(grammarAccess.getTimeAccess().getAlternatives_2(), "rule__Time__Alternatives_2");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
					put(grammarAccess.getManagerAccess().getGroup(), "rule__Manager__Group__0");
					put(grammarAccess.getManagerAccess().getGroup_4(), "rule__Manager__Group_4__0");
					put(grammarAccess.getRecipeAccess().getGroup(), "rule__Recipe__Group__0");
					put(grammarAccess.getLevelAccess().getGroup(), "rule__Level__Group__0");
					put(grammarAccess.getIngredientAccess().getGroup_0(), "rule__Ingredient__Group_0__0");
					put(grammarAccess.getWeightAccess().getGroup(), "rule__Weight__Group__0");
					put(grammarAccess.getCountAccess().getGroup(), "rule__Count__Group__0");
					put(grammarAccess.getDeviceAccess().getGroup(), "rule__Device__Group__0");
					put(grammarAccess.getCookingAccess().getGroup(), "rule__Cooking__Group__0");
					put(grammarAccess.getCookingAccess().getGroup_2(), "rule__Cooking__Group_2__0");
					put(grammarAccess.getTimeAccess().getGroup(), "rule__Time__Group__0");
					put(grammarAccess.getStepAccess().getGroup(), "rule__Step__Group__0");
					put(grammarAccess.getStepAccess().getGroup_2(), "rule__Step__Group_2__0");
					put(grammarAccess.getStepAccess().getGroup_5(), "rule__Step__Group_5__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
					put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
					put(grammarAccess.getModelAccess().getMgrAssignment(), "rule__Model__MgrAssignment");
					put(grammarAccess.getManagerAccess().getNameAssignment_1(), "rule__Manager__NameAssignment_1");
					put(grammarAccess.getManagerAccess().getUserAssignment_3(), "rule__Manager__UserAssignment_3");
					put(grammarAccess.getManagerAccess().getUserAssignment_4_1(), "rule__Manager__UserAssignment_4_1");
					put(grammarAccess.getManagerAccess().getRecipesAssignment_5(), "rule__Manager__RecipesAssignment_5");
					put(grammarAccess.getUserAccess().getNameAssignment(), "rule__User__NameAssignment");
					put(grammarAccess.getRecipeAccess().getNameAssignment_1(), "rule__Recipe__NameAssignment_1");
					put(grammarAccess.getRecipeAccess().getLevelAssignment_2(), "rule__Recipe__LevelAssignment_2");
					put(grammarAccess.getRecipeAccess().getIngredientAssignment_3(), "rule__Recipe__IngredientAssignment_3");
					put(grammarAccess.getRecipeAccess().getDeviceAssignment_4(), "rule__Recipe__DeviceAssignment_4");
					put(grammarAccess.getRecipeAccess().getCookingAssignment_5(), "rule__Recipe__CookingAssignment_5");
					put(grammarAccess.getLevelAccess().getNameAssignment_1(), "rule__Level__NameAssignment_1");
					put(grammarAccess.getIngredientAccess().getNameAssignment_0_1(), "rule__Ingredient__NameAssignment_0_1");
					put(grammarAccess.getIngredientAccess().getMeasureAssignment_0_3(), "rule__Ingredient__MeasureAssignment_0_3");
					put(grammarAccess.getWeightAccess().getWeightAssignment_0(), "rule__Weight__WeightAssignment_0");
					put(grammarAccess.getCountAccess().getCAssignment_0(), "rule__Count__CAssignment_0");
					put(grammarAccess.getDeviceAccess().getNameAssignment_1(), "rule__Device__NameAssignment_1");
					put(grammarAccess.getCookingAccess().getSAssignment_1(), "rule__Cooking__SAssignment_1");
					put(grammarAccess.getCookingAccess().getTimeAssignment_2_0(), "rule__Cooking__TimeAssignment_2_0");
					put(grammarAccess.getCookingAccess().getStepAssignment_2_2(), "rule__Cooking__StepAssignment_2_2");
					put(grammarAccess.getTimeAccess().getTimeAssignment_1(), "rule__Time__TimeAssignment_1");
					put(grammarAccess.getStepAccess().getDevAssignment_1(), "rule__Step__DevAssignment_1");
					put(grammarAccess.getStepAccess().getDev2Assignment_2_1(), "rule__Step__Dev2Assignment_2_1");
					put(grammarAccess.getStepAccess().getIngAssignment_4(), "rule__Step__IngAssignment_4");
					put(grammarAccess.getStepAccess().getIng2Assignment_5_1(), "rule__Step__Ing2Assignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RecipeDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RecipeDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
