/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.recipeDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Count</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.Count#getC <em>C</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage#getCount()
 * @model
 * @generated
 */
public interface Count extends Ingredient
{
  /**
   * Returns the value of the '<em><b>C</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>C</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' attribute.
   * @see #setC(int)
   * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage#getCount_C()
   * @model
   * @generated
   */
  int getC();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.recipeDSL.Count#getC <em>C</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>C</em>' attribute.
   * @see #getC()
   * @generated
   */
  void setC(int value);

} // Count
