/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.recipeDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Manager</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.Manager#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.Manager#getUser <em>User</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.Manager#getRecipes <em>Recipes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage#getManager()
 * @model
 * @generated
 */
public interface Manager extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage#getManager_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.recipeDSL.Manager#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>User</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.recipeDSL.User}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>User</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>User</em>' containment reference list.
   * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage#getManager_User()
   * @model containment="true"
   * @generated
   */
  EList<User> getUser();

  /**
   * Returns the value of the '<em><b>Recipes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.recipeDSL.Recipe}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Recipes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recipes</em>' containment reference list.
   * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage#getManager_Recipes()
   * @model containment="true"
   * @generated
   */
  EList<Recipe> getRecipes();

} // Manager
