/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.recipeDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLFactory
 * @model kind="package"
 * @generated
 */
public interface RecipeDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "recipeDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/RecipeDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "recipeDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RecipeDSLPackage eINSTANCE = org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.ModelImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Recipes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__RECIPES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl <em>Recipe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getRecipe()
   * @generated
   */
  int RECIPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Ingredient</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__INGREDIENT = 1;

  /**
   * The feature id for the '<em><b>Device</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__DEVICE = 2;

  /**
   * The feature id for the '<em><b>Cooking</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__COOKING = 3;

  /**
   * The number of structural features of the '<em>Recipe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.IngredientImpl <em>Ingredient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.IngredientImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getIngredient()
   * @generated
   */
  int INGREDIENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Measure</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENT__MEASURE = 1;

  /**
   * The number of structural features of the '<em>Ingredient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.MeasureImpl <em>Measure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.MeasureImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getMeasure()
   * @generated
   */
  int MEASURE = 3;

  /**
   * The number of structural features of the '<em>Measure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEASURE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.WeightImpl <em>Weight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.WeightImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getWeight()
   * @generated
   */
  int WEIGHT = 4;

  /**
   * The feature id for the '<em><b>Gramms</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEIGHT__GRAMMS = MEASURE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Weight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEIGHT_FEATURE_COUNT = MEASURE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.CountImpl <em>Count</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.CountImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getCount()
   * @generated
   */
  int COUNT = 5;

  /**
   * The feature id for the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT__COUNT = MEASURE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Count</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT_FEATURE_COUNT = MEASURE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.DeviceImpl <em>Device</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.DeviceImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getDevice()
   * @generated
   */
  int DEVICE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__NAME = 0;

  /**
   * The number of structural features of the '<em>Device</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.CookingImpl <em>Cooking</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.CookingImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getCooking()
   * @generated
   */
  int COOKING = 7;

  /**
   * The feature id for the '<em><b>Order</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COOKING__ORDER = 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COOKING__TIME = 1;

  /**
   * The feature id for the '<em><b>Step</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COOKING__STEP = 2;

  /**
   * The number of structural features of the '<em>Cooking</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COOKING_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.TimeImpl <em>Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.TimeImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getTime()
   * @generated
   */
  int TIME = 8;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__TIME = 0;

  /**
   * The number of structural features of the '<em>Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.StepImpl <em>Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.StepImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getStep()
   * @generated
   */
  int STEP = 9;

  /**
   * The feature id for the '<em><b>D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__D = 0;

  /**
   * The feature id for the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__I = 1;

  /**
   * The number of structural features of the '<em>Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Model#getRecipes <em>Recipes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Recipes</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Model#getRecipes()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Recipes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Recipe <em>Recipe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recipe</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Recipe
   * @generated
   */
  EClass getRecipe();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Recipe#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Recipe#getName()
   * @see #getRecipe()
   * @generated
   */
  EAttribute getRecipe_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Recipe#getIngredient <em>Ingredient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ingredient</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Recipe#getIngredient()
   * @see #getRecipe()
   * @generated
   */
  EReference getRecipe_Ingredient();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Recipe#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Device</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Recipe#getDevice()
   * @see #getRecipe()
   * @generated
   */
  EReference getRecipe_Device();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Recipe#getCooking <em>Cooking</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cooking</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Recipe#getCooking()
   * @see #getRecipe()
   * @generated
   */
  EReference getRecipe_Cooking();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Ingredient <em>Ingredient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ingredient</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Ingredient
   * @generated
   */
  EClass getIngredient();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Ingredient#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Ingredient#getName()
   * @see #getIngredient()
   * @generated
   */
  EAttribute getIngredient_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.recipeDSL.Ingredient#getMeasure <em>Measure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Measure</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Ingredient#getMeasure()
   * @see #getIngredient()
   * @generated
   */
  EReference getIngredient_Measure();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Measure <em>Measure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Measure</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Measure
   * @generated
   */
  EClass getMeasure();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Weight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Weight</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Weight
   * @generated
   */
  EClass getWeight();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Weight#getGramms <em>Gramms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Gramms</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Weight#getGramms()
   * @see #getWeight()
   * @generated
   */
  EAttribute getWeight_Gramms();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Count <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Count</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Count
   * @generated
   */
  EClass getCount();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Count#getCount <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Count</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Count#getCount()
   * @see #getCount()
   * @generated
   */
  EAttribute getCount_Count();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Device <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Device
   * @generated
   */
  EClass getDevice();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Device#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Device#getName()
   * @see #getDevice()
   * @generated
   */
  EAttribute getDevice_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Cooking <em>Cooking</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cooking</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Cooking
   * @generated
   */
  EClass getCooking();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Cooking#getOrder <em>Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Order</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Cooking#getOrder()
   * @see #getCooking()
   * @generated
   */
  EAttribute getCooking_Order();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.recipeDSL.Cooking#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Cooking#getTime()
   * @see #getCooking()
   * @generated
   */
  EReference getCooking_Time();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Cooking#getStep <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Step</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Cooking#getStep()
   * @see #getCooking()
   * @generated
   */
  EReference getCooking_Step();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Time <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Time
   * @generated
   */
  EClass getTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Time#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Time#getTime()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Step <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Step
   * @generated
   */
  EClass getStep();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.recipeDSL.Step#getD <em>D</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>D</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Step#getD()
   * @see #getStep()
   * @generated
   */
  EReference getStep_D();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.recipeDSL.Step#getI <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>I</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Step#getI()
   * @see #getStep()
   * @generated
   */
  EReference getStep_I();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RecipeDSLFactory getRecipeDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.ModelImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Recipes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__RECIPES = eINSTANCE.getModel_Recipes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl <em>Recipe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getRecipe()
     * @generated
     */
    EClass RECIPE = eINSTANCE.getRecipe();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECIPE__NAME = eINSTANCE.getRecipe_Name();

    /**
     * The meta object literal for the '<em><b>Ingredient</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE__INGREDIENT = eINSTANCE.getRecipe_Ingredient();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE__DEVICE = eINSTANCE.getRecipe_Device();

    /**
     * The meta object literal for the '<em><b>Cooking</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE__COOKING = eINSTANCE.getRecipe_Cooking();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.IngredientImpl <em>Ingredient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.IngredientImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getIngredient()
     * @generated
     */
    EClass INGREDIENT = eINSTANCE.getIngredient();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENT__NAME = eINSTANCE.getIngredient_Name();

    /**
     * The meta object literal for the '<em><b>Measure</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INGREDIENT__MEASURE = eINSTANCE.getIngredient_Measure();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.MeasureImpl <em>Measure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.MeasureImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getMeasure()
     * @generated
     */
    EClass MEASURE = eINSTANCE.getMeasure();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.WeightImpl <em>Weight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.WeightImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getWeight()
     * @generated
     */
    EClass WEIGHT = eINSTANCE.getWeight();

    /**
     * The meta object literal for the '<em><b>Gramms</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WEIGHT__GRAMMS = eINSTANCE.getWeight_Gramms();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.CountImpl <em>Count</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.CountImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getCount()
     * @generated
     */
    EClass COUNT = eINSTANCE.getCount();

    /**
     * The meta object literal for the '<em><b>Count</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COUNT__COUNT = eINSTANCE.getCount_Count();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.DeviceImpl <em>Device</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.DeviceImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getDevice()
     * @generated
     */
    EClass DEVICE = eINSTANCE.getDevice();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE__NAME = eINSTANCE.getDevice_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.CookingImpl <em>Cooking</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.CookingImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getCooking()
     * @generated
     */
    EClass COOKING = eINSTANCE.getCooking();

    /**
     * The meta object literal for the '<em><b>Order</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COOKING__ORDER = eINSTANCE.getCooking_Order();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COOKING__TIME = eINSTANCE.getCooking_Time();

    /**
     * The meta object literal for the '<em><b>Step</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COOKING__STEP = eINSTANCE.getCooking_Step();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.TimeImpl <em>Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.TimeImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getTime()
     * @generated
     */
    EClass TIME = eINSTANCE.getTime();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__TIME = eINSTANCE.getTime_Time();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.StepImpl <em>Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.StepImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getStep()
     * @generated
     */
    EClass STEP = eINSTANCE.getStep();

    /**
     * The meta object literal for the '<em><b>D</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__D = eINSTANCE.getStep_D();

    /**
     * The meta object literal for the '<em><b>I</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__I = eINSTANCE.getStep_I();

  }

} //RecipeDSLPackage
