/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.recipeDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLFactory
 * @model kind="package"
 * @generated
 */
public interface RecipeDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "recipeDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/RecipeDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "recipeDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RecipeDSLPackage eINSTANCE = org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.ModelImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Mgr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MGR = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.ManagerImpl <em>Manager</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.ManagerImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getManager()
   * @generated
   */
  int MANAGER = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER__NAME = 0;

  /**
   * The feature id for the '<em><b>User</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER__USER = 1;

  /**
   * The feature id for the '<em><b>Recipes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER__RECIPES = 2;

  /**
   * The number of structural features of the '<em>Manager</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANAGER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.UserImpl <em>User</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.UserImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getUser()
   * @generated
   */
  int USER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER__NAME = 0;

  /**
   * The number of structural features of the '<em>User</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl <em>Recipe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getRecipe()
   * @generated
   */
  int RECIPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Level</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__LEVEL = 1;

  /**
   * The feature id for the '<em><b>Ingredient</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__INGREDIENT = 2;

  /**
   * The feature id for the '<em><b>Device</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__DEVICE = 3;

  /**
   * The feature id for the '<em><b>Cooking</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE__COOKING = 4;

  /**
   * The number of structural features of the '<em>Recipe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECIPE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.LevelImpl <em>Level</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.LevelImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getLevel()
   * @generated
   */
  int LEVEL = 4;

  /**
   * The feature id for the '<em><b>Rating</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL__RATING = 0;

  /**
   * The number of structural features of the '<em>Level</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.IngredientImpl <em>Ingredient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.IngredientImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getIngredient()
   * @generated
   */
  int INGREDIENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Measure</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENT__MEASURE = 1;

  /**
   * The number of structural features of the '<em>Ingredient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.WeightImpl <em>Weight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.WeightImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getWeight()
   * @generated
   */
  int WEIGHT = 6;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEIGHT__WEIGHT = 0;

  /**
   * The number of structural features of the '<em>Weight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEIGHT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.CountImpl <em>Count</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.CountImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getCount()
   * @generated
   */
  int COUNT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT__NAME = INGREDIENT__NAME;

  /**
   * The feature id for the '<em><b>Measure</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT__MEASURE = INGREDIENT__MEASURE;

  /**
   * The feature id for the '<em><b>C</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT__C = INGREDIENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Count</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT_FEATURE_COUNT = INGREDIENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.DeviceImpl <em>Device</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.DeviceImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getDevice()
   * @generated
   */
  int DEVICE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__NAME = 0;

  /**
   * The number of structural features of the '<em>Device</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.CookingImpl <em>Cooking</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.CookingImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getCooking()
   * @generated
   */
  int COOKING = 9;

  /**
   * The feature id for the '<em><b>S</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COOKING__S = 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COOKING__TIME = 1;

  /**
   * The feature id for the '<em><b>Step</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COOKING__STEP = 2;

  /**
   * The number of structural features of the '<em>Cooking</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COOKING_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.TimeImpl <em>Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.TimeImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getTime()
   * @generated
   */
  int TIME = 10;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__TIME = 0;

  /**
   * The number of structural features of the '<em>Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.recipeDSL.impl.StepImpl <em>Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.recipeDSL.impl.StepImpl
   * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getStep()
   * @generated
   */
  int STEP = 11;

  /**
   * The feature id for the '<em><b>Dev</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__DEV = 0;

  /**
   * The feature id for the '<em><b>Dev2</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__DEV2 = 1;

  /**
   * The feature id for the '<em><b>Ing</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__ING = 2;

  /**
   * The feature id for the '<em><b>Ing2</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP__ING2 = 3;

  /**
   * The number of structural features of the '<em>Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.recipeDSL.Model#getMgr <em>Mgr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mgr</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Model#getMgr()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Mgr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Manager <em>Manager</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Manager</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Manager
   * @generated
   */
  EClass getManager();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Manager#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Manager#getName()
   * @see #getManager()
   * @generated
   */
  EAttribute getManager_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Manager#getUser <em>User</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>User</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Manager#getUser()
   * @see #getManager()
   * @generated
   */
  EReference getManager_User();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Manager#getRecipes <em>Recipes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Recipes</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Manager#getRecipes()
   * @see #getManager()
   * @generated
   */
  EReference getManager_Recipes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.User <em>User</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.User
   * @generated
   */
  EClass getUser();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.User#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.User#getName()
   * @see #getUser()
   * @generated
   */
  EAttribute getUser_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Recipe <em>Recipe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recipe</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Recipe
   * @generated
   */
  EClass getRecipe();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Recipe#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Recipe#getName()
   * @see #getRecipe()
   * @generated
   */
  EAttribute getRecipe_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Recipe#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Level</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Recipe#getLevel()
   * @see #getRecipe()
   * @generated
   */
  EReference getRecipe_Level();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Recipe#getIngredient <em>Ingredient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ingredient</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Recipe#getIngredient()
   * @see #getRecipe()
   * @generated
   */
  EReference getRecipe_Ingredient();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Recipe#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Device</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Recipe#getDevice()
   * @see #getRecipe()
   * @generated
   */
  EReference getRecipe_Device();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Recipe#getCooking <em>Cooking</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cooking</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Recipe#getCooking()
   * @see #getRecipe()
   * @generated
   */
  EReference getRecipe_Cooking();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Level <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Level</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Level
   * @generated
   */
  EClass getLevel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Level#getRating <em>Rating</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rating</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Level#getRating()
   * @see #getLevel()
   * @generated
   */
  EAttribute getLevel_Rating();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Ingredient <em>Ingredient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ingredient</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Ingredient
   * @generated
   */
  EClass getIngredient();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Ingredient#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Ingredient#getName()
   * @see #getIngredient()
   * @generated
   */
  EAttribute getIngredient_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Ingredient#getMeasure <em>Measure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Measure</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Ingredient#getMeasure()
   * @see #getIngredient()
   * @generated
   */
  EReference getIngredient_Measure();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Weight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Weight</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Weight
   * @generated
   */
  EClass getWeight();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.recipeDSL.Weight#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Weight</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Weight#getWeight()
   * @see #getWeight()
   * @generated
   */
  EAttribute getWeight_Weight();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Count <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Count</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Count
   * @generated
   */
  EClass getCount();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Count#getC <em>C</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>C</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Count#getC()
   * @see #getCount()
   * @generated
   */
  EAttribute getCount_C();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Device <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Device
   * @generated
   */
  EClass getDevice();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Device#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Device#getName()
   * @see #getDevice()
   * @generated
   */
  EAttribute getDevice_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Cooking <em>Cooking</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cooking</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Cooking
   * @generated
   */
  EClass getCooking();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.recipeDSL.Cooking#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>S</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Cooking#getS()
   * @see #getCooking()
   * @generated
   */
  EAttribute getCooking_S();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Cooking#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Time</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Cooking#getTime()
   * @see #getCooking()
   * @generated
   */
  EReference getCooking_Time();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.recipeDSL.Cooking#getStep <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Step</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Cooking#getStep()
   * @see #getCooking()
   * @generated
   */
  EReference getCooking_Step();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Time <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Time
   * @generated
   */
  EClass getTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.recipeDSL.Time#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Time#getTime()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.recipeDSL.Step <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Step
   * @generated
   */
  EClass getStep();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.recipeDSL.Step#getDev <em>Dev</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Dev</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Step#getDev()
   * @see #getStep()
   * @generated
   */
  EReference getStep_Dev();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.recipeDSL.Step#getDev2 <em>Dev2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Dev2</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Step#getDev2()
   * @see #getStep()
   * @generated
   */
  EReference getStep_Dev2();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.recipeDSL.Step#getIng <em>Ing</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Ing</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Step#getIng()
   * @see #getStep()
   * @generated
   */
  EReference getStep_Ing();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.recipeDSL.Step#getIng2 <em>Ing2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Ing2</em>'.
   * @see org.xtext.example.mydsl.recipeDSL.Step#getIng2()
   * @see #getStep()
   * @generated
   */
  EReference getStep_Ing2();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RecipeDSLFactory getRecipeDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.ModelImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Mgr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MGR = eINSTANCE.getModel_Mgr();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.ManagerImpl <em>Manager</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.ManagerImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getManager()
     * @generated
     */
    EClass MANAGER = eINSTANCE.getManager();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MANAGER__NAME = eINSTANCE.getManager_Name();

    /**
     * The meta object literal for the '<em><b>User</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANAGER__USER = eINSTANCE.getManager_User();

    /**
     * The meta object literal for the '<em><b>Recipes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANAGER__RECIPES = eINSTANCE.getManager_Recipes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.UserImpl <em>User</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.UserImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getUser()
     * @generated
     */
    EClass USER = eINSTANCE.getUser();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER__NAME = eINSTANCE.getUser_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl <em>Recipe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getRecipe()
     * @generated
     */
    EClass RECIPE = eINSTANCE.getRecipe();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECIPE__NAME = eINSTANCE.getRecipe_Name();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE__LEVEL = eINSTANCE.getRecipe_Level();

    /**
     * The meta object literal for the '<em><b>Ingredient</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE__INGREDIENT = eINSTANCE.getRecipe_Ingredient();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE__DEVICE = eINSTANCE.getRecipe_Device();

    /**
     * The meta object literal for the '<em><b>Cooking</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECIPE__COOKING = eINSTANCE.getRecipe_Cooking();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.LevelImpl <em>Level</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.LevelImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getLevel()
     * @generated
     */
    EClass LEVEL = eINSTANCE.getLevel();

    /**
     * The meta object literal for the '<em><b>Rating</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEVEL__RATING = eINSTANCE.getLevel_Rating();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.IngredientImpl <em>Ingredient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.IngredientImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getIngredient()
     * @generated
     */
    EClass INGREDIENT = eINSTANCE.getIngredient();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENT__NAME = eINSTANCE.getIngredient_Name();

    /**
     * The meta object literal for the '<em><b>Measure</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INGREDIENT__MEASURE = eINSTANCE.getIngredient_Measure();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.WeightImpl <em>Weight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.WeightImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getWeight()
     * @generated
     */
    EClass WEIGHT = eINSTANCE.getWeight();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WEIGHT__WEIGHT = eINSTANCE.getWeight_Weight();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.CountImpl <em>Count</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.CountImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getCount()
     * @generated
     */
    EClass COUNT = eINSTANCE.getCount();

    /**
     * The meta object literal for the '<em><b>C</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COUNT__C = eINSTANCE.getCount_C();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.DeviceImpl <em>Device</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.DeviceImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getDevice()
     * @generated
     */
    EClass DEVICE = eINSTANCE.getDevice();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE__NAME = eINSTANCE.getDevice_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.CookingImpl <em>Cooking</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.CookingImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getCooking()
     * @generated
     */
    EClass COOKING = eINSTANCE.getCooking();

    /**
     * The meta object literal for the '<em><b>S</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COOKING__S = eINSTANCE.getCooking_S();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COOKING__TIME = eINSTANCE.getCooking_Time();

    /**
     * The meta object literal for the '<em><b>Step</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COOKING__STEP = eINSTANCE.getCooking_Step();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.TimeImpl <em>Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.TimeImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getTime()
     * @generated
     */
    EClass TIME = eINSTANCE.getTime();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__TIME = eINSTANCE.getTime_Time();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.recipeDSL.impl.StepImpl <em>Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.recipeDSL.impl.StepImpl
     * @see org.xtext.example.mydsl.recipeDSL.impl.RecipeDSLPackageImpl#getStep()
     * @generated
     */
    EClass STEP = eINSTANCE.getStep();

    /**
     * The meta object literal for the '<em><b>Dev</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__DEV = eINSTANCE.getStep_Dev();

    /**
     * The meta object literal for the '<em><b>Dev2</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__DEV2 = eINSTANCE.getStep_Dev2();

    /**
     * The meta object literal for the '<em><b>Ing</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__ING = eINSTANCE.getStep_Ing();

    /**
     * The meta object literal for the '<em><b>Ing2</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP__ING2 = eINSTANCE.getStep_Ing2();

  }

} //RecipeDSLPackage
