/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.recipeDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.Step#getDev <em>Dev</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.Step#getDev2 <em>Dev2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.Step#getIng <em>Ing</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.Step#getIng2 <em>Ing2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage#getStep()
 * @model
 * @generated
 */
public interface Step extends EObject
{
  /**
   * Returns the value of the '<em><b>Dev</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.recipeDSL.Device}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dev</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dev</em>' reference list.
   * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage#getStep_Dev()
   * @model
   * @generated
   */
  EList<Device> getDev();

  /**
   * Returns the value of the '<em><b>Dev2</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.recipeDSL.Device}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dev2</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dev2</em>' reference list.
   * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage#getStep_Dev2()
   * @model
   * @generated
   */
  EList<Device> getDev2();

  /**
   * Returns the value of the '<em><b>Ing</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.recipeDSL.Ingredient}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ing</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ing</em>' reference list.
   * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage#getStep_Ing()
   * @model
   * @generated
   */
  EList<Ingredient> getIng();

  /**
   * Returns the value of the '<em><b>Ing2</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.recipeDSL.Ingredient}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ing2</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ing2</em>' reference list.
   * @see org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage#getStep_Ing2()
   * @model
   * @generated
   */
  EList<Ingredient> getIng2();

} // Step
