/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.recipeDSL.Cooking;
import org.xtext.example.mydsl.recipeDSL.Count;
import org.xtext.example.mydsl.recipeDSL.Device;
import org.xtext.example.mydsl.recipeDSL.Ingredient;
import org.xtext.example.mydsl.recipeDSL.Model;
import org.xtext.example.mydsl.recipeDSL.Recipe;
import org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage;
import org.xtext.example.mydsl.recipeDSL.Step;
import org.xtext.example.mydsl.recipeDSL.Time;
import org.xtext.example.mydsl.recipeDSL.Weight;
import org.xtext.example.mydsl.services.RecipeDSLGrammarAccess;

@SuppressWarnings("all")
public class RecipeDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private RecipeDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RecipeDSLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RecipeDSLPackage.COOKING:
				sequence_Cooking(context, (Cooking) semanticObject); 
				return; 
			case RecipeDSLPackage.COUNT:
				sequence_Count(context, (Count) semanticObject); 
				return; 
			case RecipeDSLPackage.DEVICE:
				sequence_Device(context, (Device) semanticObject); 
				return; 
			case RecipeDSLPackage.INGREDIENT:
				sequence_Ingredient(context, (Ingredient) semanticObject); 
				return; 
			case RecipeDSLPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case RecipeDSLPackage.RECIPE:
				sequence_Recipe(context, (Recipe) semanticObject); 
				return; 
			case RecipeDSLPackage.STEP:
				sequence_Step(context, (Step) semanticObject); 
				return; 
			case RecipeDSLPackage.TIME:
				sequence_Time(context, (Time) semanticObject); 
				return; 
			case RecipeDSLPackage.WEIGHT:
				sequence_Weight(context, (Weight) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Cooking returns Cooking
	 *
	 * Constraint:
	 *     (order=ID (time=Time step+=Step)*)
	 */
	protected void sequence_Cooking(ISerializationContext context, Cooking semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Measure returns Count
	 *     Count returns Count
	 *
	 * Constraint:
	 *     count=INT
	 */
	protected void sequence_Count(ISerializationContext context, Count semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RecipeDSLPackage.Literals.COUNT__COUNT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RecipeDSLPackage.Literals.COUNT__COUNT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCountAccess().getCountINTTerminalRuleCall_1_0(), semanticObject.getCount());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Device returns Device
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Device(ISerializationContext context, Device semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RecipeDSLPackage.Literals.DEVICE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RecipeDSLPackage.Literals.DEVICE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDeviceAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Ingredient returns Ingredient
	 *
	 * Constraint:
	 *     (name=ID measure=Measure)
	 */
	protected void sequence_Ingredient(ISerializationContext context, Ingredient semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RecipeDSLPackage.Literals.INGREDIENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RecipeDSLPackage.Literals.INGREDIENT__NAME));
			if (transientValues.isValueTransient(semanticObject, RecipeDSLPackage.Literals.INGREDIENT__MEASURE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RecipeDSLPackage.Literals.INGREDIENT__MEASURE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIngredientAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getIngredientAccess().getMeasureMeasureParserRuleCall_3_0(), semanticObject.getMeasure());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     recipes+=Recipe+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Recipe returns Recipe
	 *
	 * Constraint:
	 *     (name=ID ingredient+=Ingredient+ device+=Device+ cooking+=Cooking+)
	 */
	protected void sequence_Recipe(ISerializationContext context, Recipe semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Step returns Step
	 *
	 * Constraint:
	 *     (d=Device i=Ingredient)
	 */
	protected void sequence_Step(ISerializationContext context, Step semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RecipeDSLPackage.Literals.STEP__D) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RecipeDSLPackage.Literals.STEP__D));
			if (transientValues.isValueTransient(semanticObject, RecipeDSLPackage.Literals.STEP__I) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RecipeDSLPackage.Literals.STEP__I));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStepAccess().getDDeviceParserRuleCall_1_0(), semanticObject.getD());
		feeder.accept(grammarAccess.getStepAccess().getIIngredientParserRuleCall_3_0(), semanticObject.getI());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Time returns Time
	 *
	 * Constraint:
	 *     time=STRING
	 */
	protected void sequence_Time(ISerializationContext context, Time semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RecipeDSLPackage.Literals.TIME__TIME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RecipeDSLPackage.Literals.TIME__TIME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTimeAccess().getTimeSTRINGTerminalRuleCall_1_0(), semanticObject.getTime());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Measure returns Weight
	 *     Weight returns Weight
	 *
	 * Constraint:
	 *     gramms=STRING
	 */
	protected void sequence_Weight(ISerializationContext context, Weight semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RecipeDSLPackage.Literals.WEIGHT__GRAMMS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RecipeDSLPackage.Literals.WEIGHT__GRAMMS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWeightAccess().getGrammsSTRINGTerminalRuleCall_1_0(), semanticObject.getGramms());
		feeder.finish();
	}
	
	
}
