/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.recipeDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.recipeDSL.Cooking;
import org.xtext.example.mydsl.recipeDSL.Device;
import org.xtext.example.mydsl.recipeDSL.Ingredient;
import org.xtext.example.mydsl.recipeDSL.Recipe;
import org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Recipe</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl#getIngredient <em>Ingredient</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl#getDevice <em>Device</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.impl.RecipeImpl#getCooking <em>Cooking</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RecipeImpl extends MinimalEObjectImpl.Container implements Recipe
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getIngredient() <em>Ingredient</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIngredient()
   * @generated
   * @ordered
   */
  protected EList<Ingredient> ingredient;

  /**
   * The cached value of the '{@link #getDevice() <em>Device</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDevice()
   * @generated
   * @ordered
   */
  protected EList<Device> device;

  /**
   * The cached value of the '{@link #getCooking() <em>Cooking</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCooking()
   * @generated
   * @ordered
   */
  protected EList<Cooking> cooking;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RecipeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RecipeDSLPackage.Literals.RECIPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RecipeDSLPackage.RECIPE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Ingredient> getIngredient()
  {
    if (ingredient == null)
    {
      ingredient = new EObjectContainmentEList<Ingredient>(Ingredient.class, this, RecipeDSLPackage.RECIPE__INGREDIENT);
    }
    return ingredient;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Device> getDevice()
  {
    if (device == null)
    {
      device = new EObjectContainmentEList<Device>(Device.class, this, RecipeDSLPackage.RECIPE__DEVICE);
    }
    return device;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Cooking> getCooking()
  {
    if (cooking == null)
    {
      cooking = new EObjectContainmentEList<Cooking>(Cooking.class, this, RecipeDSLPackage.RECIPE__COOKING);
    }
    return cooking;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RecipeDSLPackage.RECIPE__INGREDIENT:
        return ((InternalEList<?>)getIngredient()).basicRemove(otherEnd, msgs);
      case RecipeDSLPackage.RECIPE__DEVICE:
        return ((InternalEList<?>)getDevice()).basicRemove(otherEnd, msgs);
      case RecipeDSLPackage.RECIPE__COOKING:
        return ((InternalEList<?>)getCooking()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RecipeDSLPackage.RECIPE__NAME:
        return getName();
      case RecipeDSLPackage.RECIPE__INGREDIENT:
        return getIngredient();
      case RecipeDSLPackage.RECIPE__DEVICE:
        return getDevice();
      case RecipeDSLPackage.RECIPE__COOKING:
        return getCooking();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RecipeDSLPackage.RECIPE__NAME:
        setName((String)newValue);
        return;
      case RecipeDSLPackage.RECIPE__INGREDIENT:
        getIngredient().clear();
        getIngredient().addAll((Collection<? extends Ingredient>)newValue);
        return;
      case RecipeDSLPackage.RECIPE__DEVICE:
        getDevice().clear();
        getDevice().addAll((Collection<? extends Device>)newValue);
        return;
      case RecipeDSLPackage.RECIPE__COOKING:
        getCooking().clear();
        getCooking().addAll((Collection<? extends Cooking>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RecipeDSLPackage.RECIPE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case RecipeDSLPackage.RECIPE__INGREDIENT:
        getIngredient().clear();
        return;
      case RecipeDSLPackage.RECIPE__DEVICE:
        getDevice().clear();
        return;
      case RecipeDSLPackage.RECIPE__COOKING:
        getCooking().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RecipeDSLPackage.RECIPE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case RecipeDSLPackage.RECIPE__INGREDIENT:
        return ingredient != null && !ingredient.isEmpty();
      case RecipeDSLPackage.RECIPE__DEVICE:
        return device != null && !device.isEmpty();
      case RecipeDSLPackage.RECIPE__COOKING:
        return cooking != null && !cooking.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //RecipeImpl
