/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.recipeDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.example.mydsl.recipeDSL.Device;
import org.xtext.example.mydsl.recipeDSL.Ingredient;
import org.xtext.example.mydsl.recipeDSL.RecipeDSLPackage;
import org.xtext.example.mydsl.recipeDSL.Step;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Step</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.impl.StepImpl#getDev <em>Dev</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.impl.StepImpl#getDev2 <em>Dev2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.impl.StepImpl#getIng <em>Ing</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.recipeDSL.impl.StepImpl#getIng2 <em>Ing2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StepImpl extends MinimalEObjectImpl.Container implements Step
{
  /**
   * The cached value of the '{@link #getDev() <em>Dev</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDev()
   * @generated
   * @ordered
   */
  protected EList<Device> dev;

  /**
   * The cached value of the '{@link #getDev2() <em>Dev2</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDev2()
   * @generated
   * @ordered
   */
  protected EList<Device> dev2;

  /**
   * The cached value of the '{@link #getIng() <em>Ing</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIng()
   * @generated
   * @ordered
   */
  protected EList<Ingredient> ing;

  /**
   * The cached value of the '{@link #getIng2() <em>Ing2</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIng2()
   * @generated
   * @ordered
   */
  protected EList<Ingredient> ing2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RecipeDSLPackage.Literals.STEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Device> getDev()
  {
    if (dev == null)
    {
      dev = new EObjectResolvingEList<Device>(Device.class, this, RecipeDSLPackage.STEP__DEV);
    }
    return dev;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Device> getDev2()
  {
    if (dev2 == null)
    {
      dev2 = new EObjectResolvingEList<Device>(Device.class, this, RecipeDSLPackage.STEP__DEV2);
    }
    return dev2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Ingredient> getIng()
  {
    if (ing == null)
    {
      ing = new EObjectResolvingEList<Ingredient>(Ingredient.class, this, RecipeDSLPackage.STEP__ING);
    }
    return ing;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Ingredient> getIng2()
  {
    if (ing2 == null)
    {
      ing2 = new EObjectResolvingEList<Ingredient>(Ingredient.class, this, RecipeDSLPackage.STEP__ING2);
    }
    return ing2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RecipeDSLPackage.STEP__DEV:
        return getDev();
      case RecipeDSLPackage.STEP__DEV2:
        return getDev2();
      case RecipeDSLPackage.STEP__ING:
        return getIng();
      case RecipeDSLPackage.STEP__ING2:
        return getIng2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RecipeDSLPackage.STEP__DEV:
        getDev().clear();
        getDev().addAll((Collection<? extends Device>)newValue);
        return;
      case RecipeDSLPackage.STEP__DEV2:
        getDev2().clear();
        getDev2().addAll((Collection<? extends Device>)newValue);
        return;
      case RecipeDSLPackage.STEP__ING:
        getIng().clear();
        getIng().addAll((Collection<? extends Ingredient>)newValue);
        return;
      case RecipeDSLPackage.STEP__ING2:
        getIng2().clear();
        getIng2().addAll((Collection<? extends Ingredient>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RecipeDSLPackage.STEP__DEV:
        getDev().clear();
        return;
      case RecipeDSLPackage.STEP__DEV2:
        getDev2().clear();
        return;
      case RecipeDSLPackage.STEP__ING:
        getIng().clear();
        return;
      case RecipeDSLPackage.STEP__ING2:
        getIng2().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RecipeDSLPackage.STEP__DEV:
        return dev != null && !dev.isEmpty();
      case RecipeDSLPackage.STEP__DEV2:
        return dev2 != null && !dev2.isEmpty();
      case RecipeDSLPackage.STEP__ING:
        return ing != null && !ing.isEmpty();
      case RecipeDSLPackage.STEP__ING2:
        return ing2 != null && !ing2.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //StepImpl
