/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.recipedsl.ui.internal.RecipedslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RecipeDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RecipedslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RecipedslActivator.getInstance().getInjector(RecipedslActivator.ORG_XTEXT_EXAMPLE_MYDSL_RECIPEDSL);
	}
	
}
